# Generated by Django 5.0.6 on 2024-06-21 05:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="remaining_days",
            field=models.IntegerField(default=10),
        ),
    ]
