# Generated by Django 5.0.6 on 2024-06-21 06:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_user_remaining_days"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="training",
            name="race",
        ),
        migrations.DeleteModel(
            name="Race",
        ),
        migrations.DeleteModel(
            name="Training",
        ),
    ]
