# Generated by Django 5.0.6 on 2024-06-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CPU_Horse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("stamina", models.IntegerField(default=1)),
                ("speed", models.IntegerField(default=1)),
                ("luck", models.IntegerField(default=1)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                ("emoji", models.CharField(default="🐴", max_length=10)),
                ("description", models.TextField(default="")),
            ],
        ),
        migrations.CreateModel(
            name="Horse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("stamina", models.IntegerField(default=1)),
                ("speed", models.IntegerField(default=1)),
                ("luck", models.IntegerField(default=1)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                ("emoji", models.CharField(default="🐴", max_length=10)),
                ("description", models.TextField(default="")),
            ],
        ),
    ]
