# Generated by Django 5.0.6 on 2024-06-17 01:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("horse", "0002_horse_owner_horse_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="horse",
            name="luck_increase",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="horse",
            name="speed_increase",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="horse",
            name="stamina_increase",
            field=models.IntegerField(default=0),
        ),
    ]
