# Generated by Django 5.0.6 on 2024-06-17 01:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("horse", "0003_horse_luck_increase_horse_speed_increase_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trait",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(default="")),
            ],
        ),
        migrations.AddField(
            model_name="cpu_horse",
            name="traits",
            field=models.ManyToManyField(blank=True, to="horse.trait"),
        ),
        migrations.AddField(
            model_name="horse",
            name="traits",
            field=models.ManyToManyField(blank=True, to="horse.trait"),
        ),
    ]
