# Generated by Django 5.0.6 on 2024-06-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("horse", "0005_alter_horse_luck_increase_alter_horse_speed_increase_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cpu_horse",
            name="max_luck",
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name="cpu_horse",
            name="max_speed",
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name="cpu_horse",
            name="max_stamina",
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name="horse",
            name="max_luck",
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name="horse",
            name="max_speed",
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name="horse",
            name="max_stamina",
            field=models.IntegerField(default=100),
        ),
    ]
