# Generated by Django 5.0.6 on 2024-06-21 06:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("horse", "0006_cpu_horse_max_luck_cpu_horse_max_speed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="horse",
            name="position",
            field=models.IntegerField(default=1),
        ),
    ]
