# Generated by Django 5.0.6 on 2024-06-24 01:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("horse", "0007_horse_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="horse",
            name="num_running",
            field=models.IntegerField(default=0),
        ),
    ]
