# Generated by Django 5.0.6 on 2024-06-24 05:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("horse", "0008_horse_num_running"),
    ]

    operations = [
        migrations.AddField(
            model_name="horse",
            name="num_remaining_turns",
            field=models.IntegerField(default=150),
        ),
    ]
