# Generated by Django 5.0.6 on 2024-06-26 01:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("horse", "0010_horse_remaining_racings"),
    ]

    operations = [
        migrations.AddField(
            model_name="horse",
            name="num_top",
            field=models.IntegerField(default=0),
        ),
    ]
