# Generated by Django 5.0.6 on 2024-06-26 01:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("horse", "0011_horse_num_top"),
    ]

    operations = [
        migrations.AddField(
            model_name="horse",
            name="retired",
            field=models.BooleanField(default=False),
        ),
    ]
